### ISSUE TITLE
Custom CloudFoundryServiceInfoCreator being ignored

### ISSUE THREAD

**Issue by pascalw** [cloudfoundry/java-buildpack-auto-reconfiguration#53]
I'm deploying an application to CF which uses auto-reconfiguration. I've recently added a custom Spring Cloud `CloudFoundryServiceInfoCreator` to connect to a custom service, which is working fine.

However I noticed that when running with auto-reconfiguration enabled it seems that the auto-configuration is not picking up the custom ServiceInfoCreator and `org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector` logs messages like these:

```
No suitable service info creator found for service sentry Did you forget to add a ServiceInfoCreator?
```

I would like to understand why this happening and how this is supposed to work. It seems that this project includes a copy of Spring Cloud that somehow doesn't pick up custom service info creators and seemingly also doesn't have to?

**Comment by nebhale** [comment]
This is a correct analysis.  Since auto-reconfiguration needs to know not only about the service info, but it also needs to know about the types that it is going to replace, it can only care about services that are known by the version of Spring Cloud Connectors that it is using at any given time.

This fact, that we can't auto-reconfigure arbitrary types, doesn't stop you from using Spring Cloud Connectors directly (specifically `@ServiceScan`) which is always a recommended choice.  Auto-reconfiguration is great for demos, but is so magic that using it in production is dangerous.
